### ISSUE TITLE
How can I use the module in an obstacle avoidance system in real life?

### ISSUE THREAD

**Issue by irvinmarceloc** [lojzezust/WaSR-T#5]
Hi, I'm trying to use the WaSR-T segmentation output in Jetson Nano to make an obstacle avoidance system. Is there any recommendation on how to do this? For example, I was thinking of dividing the frames into a 6x6 matrix and determining if there is a percentage greater than 20% of obstacles in it to consider it a blocked frame. And so try to make decisions, but I find some limitations such as I can not predict the trajectory of the obstacles. How could you assess the risk of collision? I have the Jetson Nano connected to a pixhawk that I put in guided mode and manage it through a script made with dronekit

**Comment by lojzezust** [comment]
Hi! I don't have much experience with collision avoidance, but here are a few ideas. 

**Collision risk and path planning:**

- Depth information would help a lot here. If you have a stereo camera system, you can use that to estimate the depth of each pixel. Otherwise, maybe try to use or train a mono-depth method. 
- After some calibration, depth can be used to determine the distance of the predicted obstacles. This may be a good estimate of collision risk.
- With depth information, you can also fit a 2D plane on the pixels predicted as water to get the navigation plane. Path finding and planning can be done on this surface.

**Trajectory prediction:** 

- Optical flow or scene flow could be used to determine the trajectory of obstacles. For example you could use optical flow to predict the future obstacle segmentation based on the current movement.
- You could also modify WaSR-T to predict also future segmentation, but that would require annotations also for a future frame and I'm not sure how well it would work.

**Obstacle instances:**

- Combining depth and segmentation, you could probably determine individual objects (e.g. all pixels that belong to a boat). Maybe it will be easier for you to plan with respect to individual obstacles, rather than pixels.

Hope this helps!

**Comment by irvinmarceloc** [comment]
Hello.
Thank you very much. I will be doing some research. I opened a repository on my GitHub account to try obstacle evasion, but it's still in its early stages. I would like to use WaSR-T with computer vision system if you agree.
If I achieve good results in real life, I will let you know.
https://github.com/irvinmarceloc/Sistema-Navegaci-n-ASV

**Comment by lojzezust** [comment]
Awesome, feel free to use WaSR-T. I'm looking forward to the results of your work!

**Comment by irvinmarceloc** [comment]
I intend to adjust the camera for an approximate 20-meter vision range ahead, then take the segmented output and divide it into sectors to determine obstacle locations. I then use this data to feed into a navigation system built with DroneKit, utilizing a Pixhawk. Currently, I don't believe the Jetson Nano supports a depth sensing system. However, if this setup works as intended, I will then attempt to incorporate a depth sensor. 
I have this schematic, in the photo you can see the ASV that I am using.  I hope it can work.

![image](https://github.com/lojzezust/WaSR-T/assets/64157096/97fe329e-36c1-4e47-956c-f37da9ee295f)

![image](https://github.com/lojzezust/WaSR-T/assets/64157096/f7076f8c-bc47-4063-ae91-e0ee22f119d2)

![image](https://github.com/lojzezust/WaSR-T/assets/64157096/942e2e91-743e-4546-b350-d1e095ead17d)
